version: '2'
services:
  matchandtrade-api:
    image: rafaelsantosbra/matchandtrade-api:0.0-SNAPSHOT
    container_name: matchandtrade-api
    ports:
     - "8080:8080"
    volumes:
     - ./config:/matchandtrade/config
     - ./database:/matchandtrade/database
     - ./log:/matchandtrade/log
